version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=chiefonboarding
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - global

  web:
    restart: always
    container_name: web
    build:
      context: ./back/Dockerfile
    ports:
      - "8000:8000"
    command: gsh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn back.wsgi -b 0.0.0.0:8000"
    environment:
      SECRET_KEY=somethingsupersecret
      BASE_URL=https://yoursite.com
      DATABASE_URL=postgres://postgres:postgres@db:5432/chiefonboarding
      REDIS_URL=redis://redis:6379
      ALLOWED_HOST=https://yoursite.com
    depends_on:
      - db
    networks:
      - global

  caddy:
    image: caddy:alphine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    newtorks:
      - global

  redis:
    restart: unless-stopped 
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - global

  celery:
    command: sh -c "celery --workdir=back -A back worker --beat -l info" 
    restart: unless-stopped
    depends_on:
      - web
      - redis
    networks:
      - global

volumes:
  pgdata:
  caddy_data:
  caddy_config:
