name: Release to deploy repo 
on:
  push:
    branches:
      - test-deploy
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build source
      env:
        BASE_URL: /
      run: |
        cd front
        npm install
        npx nuxt build
        node ./postinstall
    - name: Package files
      run: |
        rm -rf front/
    - name: Git push deploy part 
      run: |
        git config --global user.name 'ChiefOnboarding'
        git config --global user.email 'noreply@chiefonboarding.com'
        rm -rf .git
        git init
        git add -A 
        git commit -m "Test deploy" 
        git status
        git push origin main:deploy

