name: Build container and push to DockerHub
on:
  create:
    tags:
      - v* 
jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./back/Dockerfile
        push: true
        tags: |
          chiefonboarding/chiefonboarding:latest
          chiefonboarding/chiefonboarding:${GITHUB_REF/refs\/tags\//}
