name: Release 
on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build source
      env:
        BASE_URL: /
      run: |
        cd front
        npm install
        npx nuxt build
        node ./postinstall
    - name: Package files
      run: |
        rm -rf front/
    - name: Upload pakage to release
      uses: actions/upload-artifact@v2
      with:
        name: chiefonboarding-prebuild
        path: . 

