name: Release 
on:
  push:
    branches:
      - feat-auto-create-release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build source
      env:
        baseURL: /
      run: |
        cd front
        npm run build
    - name: Package files
      run: |
        rm -rf front/
        sleep 120
        tar cfz --warning=no-file-changed chiefonboarding.tar.gz .
    - name: Upload pakage to release
      uses: actions/upload-artifact@v2
      with:
        name: chiefonboarding-prebuild.tar.gz 
        path: build/release/chiefonboarding-prebuild.tar.gz

