name: update_docs
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          npm install retypeapp --global
          cd docs
          retype build
      - name: Uploading files with rclone 
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: sync .docs/retype/ storage:/caddy/chief_docs/
